###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [12]:
# code here
import numpy as np

# Create random 4x3 matrix with values between 0–100
arr = np.random.randint(0, 101, (4, 3))
print("Original Array:\n", arr)

# i. Sort each row
sorted_arr = np.sort(arr, axis=1)
print("\n(i) Sorted each row:\n", sorted_arr)

# ii. Sort based on 2nd column (column index 1)
sorted_by_col2 = arr[arr[:, 1].argsort()]
print("\n(ii) Sorted by 2nd column:\n", sorted_by_col2)

# iii. Sort based on max value in each row
sorted_by_row_max = arr[np.max(arr, axis=1).argsort()]
print("\n(iii) Sorted by max value in each row:\n", sorted_by_row_max)

# iv. Sort based on all element values (flatten and reshape)
sorted_by_elements = np.sort(arr, axis=None).reshape(arr.shape)
print("\n(iv) Sorted by all elements:\n", sorted_by_elements)



Original Array:
 [[45 96 33]
 [10 18 57]
 [28 86 49]
 [58 69 28]]

(i) Sorted each row:
 [[33 45 96]
 [10 18 57]
 [28 49 86]
 [28 58 69]]

(ii) Sorted by 2nd column:
 [[10 18 57]
 [58 69 28]
 [28 86 49]
 [45 96 33]]

(iii) Sorted by max value in each row:
 [[10 18 57]
 [58 69 28]
 [28 86 49]
 [45 96 33]]

(iv) Sorted by all elements:
 [[10 18 28]
 [28 33 45]
 [49 57 58]
 [69 86 96]]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [13]:
# code here
 

# Given data
marks = np.array([
    [13, 10,  9, 33],
    [63, 46, 90, 42],
    [39, 76, 13, 29],
    [82,  9, 29, 78],
    [67, 61, 59, 36]
])

extra_subject = np.array([41, 87, 72, 36, 92])
rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])

# i. Add marks of extra subject as a new column
marks = np.column_stack((marks, extra_subject))
print("After adding extra subject:\n", marks)

# ii. Add two new students (rows)
marks = np.vstack((marks, rec1, rec2))
print("\nAfter adding two new students:\n", marks)

# iii. Add extra column for total marks (sum across subjects)
total_marks = marks.sum(axis=1)
marks = np.column_stack((marks, total_marks))
print("\nAfter adding total marks column:\n", marks)

# iv. Sort in non-ascending order (by total marks column)
# (Total marks is now the last column, index = -1)
sorted_marks = marks[marks[:, -1].argsort()[::-1]]

print("\nSorted by total marks (descending):\n", sorted_marks)

# Show top 2 rows
print("\nTop 2 students:\n", sorted_marks[:2])


After adding extra subject:
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]

After adding two new students:
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]

After adding total marks column:
 [[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]

Sorted by total marks (descending):
 [[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]
 [ 63  46  90  42  87 328]
 [ 67  61  59  36  92 315]
 [ 82   9  29  78  36 234]
 [ 39  76  13  29  72 229]
 [ 13  10   9  33  41 106]]

Top 2 students:
 [[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [14]:
# code here
 
# Given array
arr = np.array([
    [1, 2, 3, 3, 1, 1],
    [0, 9, 1, 2, 8, 8],
    [1, 2, 3, 8, 8, 8],
    [1, 2, 3, 3, 1, 1]
])

# i. Unique rows
unique_rows = np.unique(arr, axis=0)
print("Unique Rows:\n", unique_rows)

# ii. Unique columns
unique_cols = np.unique(arr, axis=1)
print("\nUnique Columns:\n", unique_cols)


Unique Rows:
 [[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Unique Columns:
 [[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [15]:
# code here

# Example 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original Array:\n", arr)

# Flip along both axes
flipped = np.flip(arr)

print("\nFlipped along both axes:\n", flipped)


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped along both axes:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [16]:
# code here
arr = np.array([
    [1, 2, 3, 4, 5],
    [10, -3, 30, 4, 5],
    [3, 2, 5, -4, 5],
    [9, 7, 3, 6, 5]
])

X = 6

# Find row indices where any element > X
rows = np.where(np.any(arr > X, axis=1))[0]

print("Row numbers having element larger than", X, ":\n", rows)

Row numbers having element larger than 6 :
 [1 3]


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [ ]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [17]:
# code here
arr1 = np.arange(3)       # [0 1 2]
arr2 = np.arange(3, 7)    # [3 4 5 6]
arr3 = np.arange(7, 10)   # [7 8 9]

# Combine and flatten into one 1D array
flat_arr = np.concatenate((arr1, arr2, arr3))

print("Flattened 1D array:\n", flat_arr)

Flattened 1D array:
 [0 1 2 3 4 5 6 7 8 9]


### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [18]:
# code here
import numpy as np

# Given data
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

print("Original Array:\n", arr)

# Flatten to 1D for easy manipulation
arr_flat = arr.flatten()

# Find min and max values
min_val = np.min(arr_flat)
max_val = np.max(arr_flat)

print("\nMinimum value:", min_val)
print("Maximum value:", max_val)

# Remove min and max values
arr_removed = arr_flat[(arr_flat != min_val) & (arr_flat != max_val)]

print("\nArray after removing min and max elements:\n", arr_removed)


Original Array:
 [[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 103 627 920 824 356 825
  173 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211
  771 270 308 231 952 514 699 702 433 900 373 318 998 265 503 320 230 324
  922 967 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930
  325 729 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528
  395 525 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859
  618 226 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748
  291 194 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207
  883 588]]

Minimum value: 103
Maximum value: 998

Array after removing min and max elements:
 [448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [19]:
# code here
import numpy as np

# Given array
np.random.seed(42)
arr = np.random.randint(100, 700, 20)
print("Original Array:\n", arr)

# 1️⃣ Limit array elements between 100 and 200
arr_clipped = np.clip(arr, 100, 200)
print("\nArray after limiting values between 100–200:\n", arr_clipped)

# 2️⃣ Sort the array
arr_sorted = np.sort(arr_clipped)
print("\nSorted Array:\n", arr_sorted)

# 3️⃣ Cumulative sum of sorted array
arr_cumsum = np.cumsum(arr_sorted)
print("\nCumulative Sum:\n", arr_cumsum)


Original Array:
 [202 535 370 206 171 120 221 566 314 430 558 187 472 199 230 408 443 591
 513 485]

Array after limiting values between 100–200:
 [200 200 200 200 171 120 200 200 200 200 200 187 200 199 200 200 200 200
 200 200]

Sorted Array:
 [120 171 187 199 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200]

Cumulative Sum:
 [ 120  291  478  677  877 1077 1277 1477 1677 1877 2077 2277 2477 2677
 2877 3077 3277 3477 3677 3877]


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [20]:
# code here
import numpy as np

# Given array (values between 0 and 1)
np.random.seed(10)
arr = np.random.random(20)
print("Original Array:\n", arr)

# 1️⃣ Round elements to 3 decimal places
arr = np.round(arr, 3)
print("\nRounded Array:\n", arr)

# 2️⃣ Check percentile relationships
p0 = np.percentile(arr, 0)
p100 = np.percentile(arr, 100)

print("\n0th Percentile:", p0)
print("Minimum value :", np.min(arr))
print("100th Percentile:", p100)
print("Maximum value  :", np.max(arr))

print("\n0th Percentile == Min Value →", np.isclose(p0, np.min(arr)))
print("100th Percentile == Max Value →", np.isclose(p100, np.max(arr)))

# 3️⃣ Find difference between 51st and 50th percentiles
p51 = np.percentile(arr, 51)
p50 = np.percentile(arr, 50)
diff = p51 - p50

print("\n51st Percentile:", p51)
print("50th Percentile:", p50)
print("Difference (p51 - p50):", diff)


Original Array:
 [0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578]

Rounded Array:
 [0.771 0.021 0.634 0.749 0.499 0.225 0.198 0.761 0.169 0.088 0.685 0.953
 0.004 0.512 0.813 0.613 0.722 0.292 0.918 0.715]

0th Percentile: 0.004
Minimum value : 0.004
100th Percentile: 0.953
Maximum value  : 0.953

0th Percentile == Min Value → True
100th Percentile == Max Value → True

51st Percentile: 0.62749
50th Percentile: 0.6234999999999999
Difference (p51 - p50): 0.003990000000000049
